### ISSUE TITLE
CreateTag panic with using filesystem without cache

### ISSUE THREAD

**Issue by janakerman** [go-git/go-git#255]
I've stumbled into a panic when attempting to create a tag (`CreateTag`) that seems to happen only when using a filesystem with a `nil` cache.

<details>
    <summary>Panic</summary>

```
--- FAIL: Test_Issue (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13a4356]

goroutine 6 [running]:
testing.tRunner.func1.1(0x1410640, 0x17f2370)
	/usr/local/opt/go/libexec/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc000131680)
	/usr/local/opt/go/libexec/src/testing/testing.go:943 +0x3f9
panic(0x1410640, 0x17f2370)
	/usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x166
github.com/go-git/go-git/v5.(*CommitOptions).Validate(0x0, 0xc00018a390, 0x1442b20, 0xc00000f880)
	/Users/janakerman/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/options.go:423 +0x26
github.com/go-git/go-git/v5.(*Worktree).Commit(0xc00018a510, 0x14974e1, 0x3, 0x0, 0x0, 0x0, 0x0, 0x1d00108, 0xc00014cde8)
	/Users/janakerman/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/worktree_commit.go:22 +0x68
github.com/janakerman/mage-play/version_test.Test_Issue(0xc000131680)
	/Users/janakerman/dev/mage-play/version/version_test.go:115 +0x451
testing.tRunner(0xc000131680, 0x14b5cb8)
	/usr/local/opt/go/libexec/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:1042 +0x357
FAIL	github.com/janakerman/mage-play/version	0.019s
FAIL
```

</details>

<details>
    <summary>Test to reproduce</summary>

```
func Test_Issue(t *testing.T) {
	rootDir := os.TempDir() + "repo"
	os.MkdirAll(rootDir, 0777)

	// Cache is needed to avoid nil panic.
	repo, err := git.Init(filesystem.NewStorage(osfs.New(rootDir+".git"), nil), osfs.New(rootDir))
	if err != nil {
		panic(err)
	}

	w, err := repo.Worktree()
	if err != nil {
		panic(err)
	}

	firstHash, err := w.Commit("msg", nil)
	if err != nil {
		panic(err)
	}

	_, err = repo.CreateTag("v1.0.0", firstHash, nil)
	if err != nil {
		panic(err)
	}
}
```

</details>

The nil pointer dereference is [here](https://github.com/go-git/go-git/blob/master/storage/filesystem/object.go#L388). Initialising the filesystem storage with a cache seems to resolve the issue:
```
filesystem.NewStorage(osfs.New(repoDir+".git"), cache.NewObjectLRUDefault())
```

**Comment by mcuadros** [comment]
The cache is not nillable. Is mandatory sorry.
