### ISSUE TITLE
Guard against concurrent map access

### ISSUE THREAD

**Issue by mpldr** [go-git/go-git#903]
During testing of my program I found this concurrent map-access crash:

```
fatal error: concurrent map read and map write

goroutine 66 [running]:
github.com/go-git/go-git/v5/plumbing/format/idxfile.(*MemoryIndex).FindHash(0xc00015e000, 0x5279e500ac9df344?)
	github.com/go-git/go-git/v5@v5.10.0/plumbing/format/idxfile/idxfile.go:177 +0x5b
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).decodeObjectAt(0xc0003ea158, 0xc0001143c0, 0x7f5cab109f45?)
	github.com/go-git/go-git/v5@v5.10.0/storage/filesystem/object.go:473 +0x34
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).getFromPackfile(0xc0003ea158, {0x23, 0xe4, 0x88, 0x32, 0x48, 0xf0, 0x47, 0x2d, 0x80, ...}, ...)
	github.com/go-git/go-git/v5@v5.10.0/storage/filesystem/object.go:466 +0x2e5
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).EncodedObject(0xc0003ea158, 0x1, {0x23, 0xe4, 0x88, 0x32, 0x48, 0xf0, 0x47, 0x2d, ...})
	github.com/go-git/go-git/v5@v5.10.0/storage/filesystem/object.go:318 +0x51
github.com/go-git/go-git/v5/plumbing/object.GetCommit({0x55c9ad2dad80, 0xc0003ea140}, {0x23, 0xe4, 0x88, 0x32, 0x48, 0xf0, 0x47, 0x2d, ...})
	github.com/go-git/go-git/v5@v5.10.0/plumbing/object/commit.go:71 +0x39
github.com/go-git/go-git/v5.(*Repository).CommitObject(...)
	github.com/go-git/go-git/v5@v5.10.0/repository.go:1418
git.sr.ht/~mpldr/gogit/internal/types.(*Repo).Commit(0xc0003e4180, {0xc0003d62d2?, 0x40?})
	git.sr.ht/~mpldr/gogit/internal/types/repo.go:119 +0x8c
git.sr.ht/~mpldr/gogit/internal/handler.(*Handler).repoHandler.commitHandler.func2(0xc0003d624b?)
	git.sr.ht/~mpldr/gogit/internal/handler/commit.go:24 +0x2a5
git.sr.ht/~mpldr/gogit/internal/handler.(*Handler).repoHandler(0xc00013e600?, 0xc0003d60c0?, 0xc0003e4180)
	git.sr.ht/~mpldr/gogit/internal/handler/repo.go:21 +0x20d
git.sr.ht/~mpldr/gogit/internal/handler.(*Handler).Serve(0xc0000a2030, 0xc00013e600)
	git.sr.ht/~mpldr/gogit/internal/handler/serve-http.go:30 +0x4f9
github.com/valyala/fasthttp.(*Server).serveConn(0xc0000a8000, {0x55c9ad2db1b8?, 0xc00006c000})
	github.com/valyala/fasthttp@v1.50.0/server.go:2359 +0x11d4
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0000b81e0, 0xc000088000)
	github.com/valyala/fasthttp@v1.50.0/workerpool.go:224 +0xa4
github.com/valyala/fasthttp.(*workerPool).getCh.func1()
	github.com/valyala/fasthttp@v1.50.0/workerpool.go:196 +0x32
created by github.com/valyala/fasthttp.(*workerPool).getCh in goroutine 1
	github.com/valyala/fasthttp@v1.50.0/workerpool.go:195 +0x1ab
```

From what I can see, this is because of a missing mutex on `(*idxfile.MemoryIndex).offsetHash`

https://github.com/go-git/go-git/blob/master/plumbing/format/idxfile/idxfile.go#L60

**Comment by pjbgf** [comment]
Closing as this change is already in `v6-exp` as per #773.
